import type { Metadata } from "next";
import "./globals.css";
import { Rubik } from "next/font/google";
import { DataContextProvider } from "@/backend/datacontext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rubik = Rubik({
  weight: ['400', "600", '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik'
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased`}
      >
        <DataContextProvider>
          {children}

        </DataContextProvider>
      </body>
    </html>
  );
}
